// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBklh9FXdWDMyFxho4Z_y3k7-WnpYmlfjA',
    appId: '1:576844263973:web:d307ed80ed3f9b7b8705cc',
    messagingSenderId: '576844263973',
    projectId: 'market-app-ebdf3',
    authDomain: 'market-app-ebdf3.firebaseapp.com',
    storageBucket: 'market-app-ebdf3.appspot.com',
    measurementId: 'G-LWNW80518S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKIAcMFCo79GYgFp-f0N9GiDIeu2zk_w',
    appId: '1:576844263973:android:4a26686e85dcd3dc8705cc',
    messagingSenderId: '576844263973',
    projectId: 'market-app-ebdf3',
    storageBucket: 'market-app-ebdf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rSMq5tEngP4Y4O_VHsyRtGFdj7nkGS8',
    appId: '1:576844263973:ios:02fb8113aefa96d58705cc',
    messagingSenderId: '576844263973',
    projectId: 'market-app-ebdf3',
    storageBucket: 'market-app-ebdf3.appspot.com',
    iosClientId: '576844263973-f4l4jf33af74gt67346mbqflp7d1jncm.apps.googleusercontent.com',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-rSMq5tEngP4Y4O_VHsyRtGFdj7nkGS8',
    appId: '1:576844263973:ios:49ed310d5a7bff478705cc',
    messagingSenderId: '576844263973',
    projectId: 'market-app-ebdf3',
    storageBucket: 'market-app-ebdf3.appspot.com',
    iosClientId: '576844263973-ni3o4nudfi7knf6o4qnkql7k4n0lcgkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.market.RunnerTests',
  );
}
